---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hdfs.opencore.com
spec:
  group: stable.opencore.com
  names:
    kind: HDFS
    plural: hdfs
    singular: hdfs
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                nameNode:
                  type: object
                  properties:
                    minNodeCount:
                      type: integer
                      minimum: 1
                      # default: 2
                    maxNodeCount:
                      type: integer
                      minimum: 1
                      # default: 2
                    config:
                      additionalProperties:
                        type: string
                hadoopConf:
                  additionalProperties:
                    type: string
                  type: object
                hadoopConfigMap:
                  type: string
