---
apiVersion: stable.opencore.com/v1
kind: Kafka

metadata:
  name: kafka-prod
  labels:
    environment: production
spec:
  broker:
    zooKeeperRef: ...

    # TODO: We are unsure if we actually need a min node count here
    nodeSelector:
      ...
    listener:
      - type: unauthenticated
        port: 9092
      - type: kerberos
        tls_encryption: true
        ...
      - type: tls
        tls_encryption: true
        ...
      - type: kerberos
        tls_encryiption: false
        advertisedListener: ...
        ...


    config:
      linger.ms: 500
      ...
    configMapRef:
      name: special-config
      priority: 1
    roleConfig:
      - selector:
          diskType: ssd
        config:
          ...
        configMapRef:
      - selector:
          hostName: server-01.opencore.io
        config:
          ...
        configMapRef: ...

  # TODO: Filter and redaction rules(for example: DEBUG to Elastic cluster A, ERROR to Elastic cluster B)
 logging:
    retention: ...
    rollingInterval: ...
    defaultExternalLogStorageRef: prod-elk
    # TODO: Refactor these definitions to separate objects to make them re-useable
    brokerLog:
      collect: true
      externalLogStorageRef: prod-audit-elk
      logLevel:
        ...
    brokerStdout:
      collect: true

  metrics:
    metricsStorageRef: ...
    blacklist: ... # Metriken, die nicht reported werden sollen
    whitelist: ...

# TODO: Add the concept of an external client - 10.0.0.5 should always be running a kafka consumer,
# we would grab the jmx metrics as well and export them
# "ExternanConsumer" -> unmanaged but known

# How to treat broker-ids?


# MirrorMaker2
# TODO: This is far removed from being complete
---
apiVersion: stable.opencore.com/v1
kind: MirrorMaker
metadata:
  name: mirrormaker-prod
  labels:
    environment: production
spec:
  # [standalone, legacy, connect, cluster]
  mode: standalone
  nodeSelector:
    ...
  kafkaClusters:
    - kafka-prod
    - kafka-dev
    - edge-kafka-unmanaged


---
apiVersion: stable.opencore.com/v1
kind: KafkaReplication
...

sourceCluster: kafka-prod
targetCluster: kafka-dev
sourceTopic: foobar
  topicSetRef:
targetTopic: barfoo
offsets: true
config: false

---
apiVersion: stable.opencore.com/v1
kind: KafkaTopicSet
...
